project:
  type: website
  output-dir: docs
  render:
    - eda.qmd
    - Modeling.qmd

website:
  title: "ST558 Project 3 â€“ Derek Chao"
  navbar:
    left:
      - text: "EDA"
        href: eda.html
      - text: "Modeling"
        href: Modeling.html

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full
